CREATE ROLE :MIGRATOR_ROLE WITH LOGIN PASSWORD :'MIGRATOR_PASSWORD';
GRANT CREATE, USAGE ON SCHEMA public TO :MIGRATOR_ROLE;

CREATE ROLE :APP_ROLE WITH LOGIN PASSWORD :'APP_PASSWORD';
GRANT USAGE ON SCHEMA public TO :APP_ROLE;
GRANT CONNECT ON DATABASE :DATABASE_NAME TO :APP_ROLE;

\c :DATABASE_NAME

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :APP_ROLE;
ALTER DEFAULT PRIVILEGES FOR ROLE :MIGRATOR_ROLE IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :APP_ROLE;